services:
  rockylinux:
    image: rockylinux:9-minimal
    build: 
      context: .
      dockerfile: Dockerfile
    command: "/bin/bash"
    volumes:
      - rocky-data:/root
    ports:
      - "2222:22"
volumes:
  rocky-data: