services:
  rockylinux:
    image: rockylinux:9-minimal
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash"]
    container_name: rocky9
    ports:
      - "2222:22"
    tty: true
    stdin_open: true
    privileged: true